### ISSUE TITLE
What is "BUND" in Region documentation ? 

### ISSUE THREAD

**Issue by AvgustPol** [sfakir/feiertagejs#54]
What is "BUND" in Region documentation? 

![image](https://user-images.githubusercontent.com/29002229/202505729-828db2f3-b8de-4e74-b90d-50c9361881c9.png)

From wiki which were mentioned in documentation : 
https://de.wikipedia.org/wiki/Land_(Deutschland)#Amtliche_bzw._Eigenbezeichnungen

![image](https://user-images.githubusercontent.com/29002229/202505919-37ba5ef5-f5a1-4339-a811-d85830175f9f.png)

**Comment by AvgustPol** [comment]
![image](https://user-images.githubusercontent.com/29002229/202506678-2e79cd63-b666-4a9f-9300-54a0a9096d78.png)

I can't find `Gesamt-Deutschland` at https://de.wikipedia.org/wiki/Land_(Deutschland)#Amtliche_bzw._Eigenbezeichnungen

**Comment by sfakir** [comment]
Thank you for the feedback, I updated the docs. 
Does this answer the question?

* https://github.com/sfakir/feiertagejs/blob/master/docs.md

**Comment by AvgustPol** [comment]
I`ve had to spend some time to investigate the difference, It was still not clear after your update but it helped me to understand so I`d suggest this explanation: 

"ALL" refers to every holiday which are valid in AT LEAST one region 
"BUND" refers to holidays which are valid in every region ("bundesweit"). So a holiday which only applies to one state will not be included.

do you agree with it ?

**Comment by sfakir** [comment]
Hi @AvgustPol , yes exactly.
Thank you for the comment, I will update the docs.
